name: integration test all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go integration-test.yml"

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # docker on MacOS is not supported by GitHub actions

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: integration
        run: docker build . -f test/integration/integration.dockerfile -t integration && docker run integration
