name: integration test all
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PRISMA_TELEMETRY_INFORMATION: "prisma-client-go integration-test.yml"

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # macos is not supported by GitHub actions

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - uses: satackey/action-docker-layer-caching@v0.0.10
        with:
          key: docker-${{ runner.os }}-${{ github.workflow }}-{hash}

      - name: integration
        run: docker build . -f test/integration/integration.dockerfile -t integration && docker run integration
